/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as IndexRouteImport } from './routes/index'

const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/generator': typeof GeneratorRoute
  '/manifesto': typeof ManifestoRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/generator': typeof GeneratorRoute
  '/manifesto': typeof ManifestoRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/generator': typeof GeneratorRoute
  '/manifesto': typeof ManifestoRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/generator'
    | '/manifesto'
    | '/scheduler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/generator'
    | '/manifesto'
    | '/scheduler'
  id:
    | '__root__'
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/generator'
    | '/manifesto'
    | '/scheduler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  DashboardRoute: typeof DashboardRoute
  GeneratorRoute: typeof GeneratorRoute
  ManifestoRoute: typeof ManifestoRoute
  SchedulerRoute: typeof SchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  DashboardRoute: DashboardRoute,
  GeneratorRoute: GeneratorRoute,
  ManifestoRoute: ManifestoRoute,
  SchedulerRoute: SchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
